name: Docker Image for Pushes

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.io
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GIT_HUB_TOKEN }}
    # https://github.com/docker/setup-qemu-action#usage
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.1.0
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        context: .
        #platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        tags: aunefyren/poenskelisten:beta
