name: Docker Image for Pushes

on:
  push:
    branches: [main]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          aunefyren/poenskelisten
          ghcr.io/${{ github.repository_owner }}/poenskelisten
        tags: |
          type-raw,value=beta
        flavor: |
          latest=false
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GIT_HUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        builder: ${{ steps.buildx.outputs.name }}
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/386
        push: true
        context: .
        tags: ${{ steps.meta.outputs.tags }}