name: Update Release Tag in File

on:
  push:
    tags:
      - '*'  # Triggers on any tag push

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            ref: ${{ github.ref_name }}
            token: ${{ secrets.GIT_HUB_TOKEN }}

        - name: Get the default branch
          id: default_branch
          run: echo "DEFAULT_BRANCH=$(git remote show origin | awk '/HEAD branch/ {print $NF}')" >> $GITHUB_ENV
  
        - name: Switch to default branch
          run: |
            git checkout $DEFAULT_BRANCH
            git pull origin $DEFAULT_BRANCH 

        - name: Replace template string in file
          run: sed -i 's/{{RELEASE_TAG}}/${{ github.event.release.tag_name }}/g' config/config.go
          
        - name: Commit and push changes
          run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git commit -am "Update release tag to ${TAG_NAME}"
            git push
